import {
    USER,
    POST,
    COMMENT,
    NOTIFICATION,
    FRIEND_REQUEST,
    STORY,
    STATS,
    REPORT
} from "./interface";

export const mockChatBot: USER = {
    id: "37a847f194714e83d6dae894",
    email: "chatbot@example.com",
    gender: "OTHER",
    fullName: "Chat Bot",
    dateOfBirth: "2004-05-12",
    avatarPhotoUrl: "/ChatBotAvatar.png",
    coverPhotoUrl: "",
    followers: [],
    following: [],
    friends: [],
    posts: [],
    status: "ACTIVE",
    celebrity: false,
    bio: {
        id: "37a847f194714e83d6dae894",
        user: {} as USER,
        bioText: "",
        liveIn: "",
        relationship: "",
        workplace: "Chat Bot",
        education: "",
        phone: "",
        hometown: "",
    },
    role: "USER",
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2023-01-01T00:00:00Z",
};

export const mockUsers: USER[] = [
    {
        id: "1",
        email: "john.doe@example.com",
        gender: "MALE",
        fullName: "John Doe",
        dateOfBirth: "2000-04-15",
        avatarPhotoUrl: "/placeholder.svg",
        coverPhotoUrl: "/cover-placeholder.svg",
        followers: [],
        following: [],
        friends: [{
            id: "2",
            email: "john.doe@example.com",
            gender: "MALE",
            fullName: "John Doe",
            dateOfBirth: "2000-04-15",
            avatarPhotoUrl: "/placeholder.svg",
            coverPhotoUrl: "/cover-placeholder.svg",
            followers: [],
            following: [],
            friends: [],
            posts: [],
            status: "ACTIVE",
            bio: {
                id: "2",
                user: {} as USER,
                bioText: "Software Engineer",
                liveIn: "New York",
                relationship: "Single",
                workplace: "Tech Company",
                education: "University of Technology",
                phone: "123-456-7890",
                hometown: "Los Angeles",
                createdAt: "2023-01-01T00:00:00Z",
                updatedAt: "2023-01-01T00:00:00Z",
            },
            celebrity: false,
            role: "USER",
            createdAt: "2023-01-01T00:00:00Z",
            updatedAt: "2023-01-01T00:00:00Z",
        },],
        bio: {
            id: "1",
            user: {} as USER,
            bioText: "Software Engineer",
            liveIn: "New York",
            relationship: "Single",
            workplace: "Tech Company",
            education: "University of Technology",
            phone: "123-456-7890",
            hometown: "Los Angeles",
            createdAt: "2023-01-01T00:00:00Z",
            updatedAt: "2023-01-01T00:00:00Z",
        },
        celebrity: false,
        posts: [],
        status: "ACTIVE",
        role: "ADMIN",
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "2",
        email: "jane.smith@example.com",
        gender: "FEMALE",
        fullName: "Jane Smith",
        dateOfBirth: "1992-02-02",
        avatarPhotoUrl: "/placeholder.svg",
        coverPhotoUrl: "/cover-placeholder.svg",
        followers: [],
        following: [],
        posts: [],
        status: "ACTIVE",
        celebrity: false,
        friends: [{
            id: "1",
            email: "john.doe@example.com",
            gender: "MALE",
            fullName: "John Doe",
            dateOfBirth: "2000-04-15",
            avatarPhotoUrl: "/placeholder.svg",
            coverPhotoUrl: "/cover-placeholder.svg",
            followers: [],
            following: [],
            friends: [],
            posts: [],
            status: "ACTIVE",
            celebrity: false,
            bio: {
                id: "1",
                user: {} as USER,
                bioText: "Software Engineer",
                liveIn: "New York",
                relationship: "Single",
                workplace: "Tech Company",
                education: "University of Technology",
                phone: "123-456-7890",
                hometown: "Los Angeles",
                createdAt: "2023-01-01T00:00:00Z",
                updatedAt: "2023-01-01T00:00:00Z",
            },
            role: "USER",
            createdAt: "2023-01-01T00:00:00Z",
            updatedAt: "2023-01-01T00:00:00Z",
        },],
        bio: {
            id: "2",
            user: {} as USER,
            bioText: "Graphic Designer",
            liveIn: "Alice Williams",
            relationship: "In a relationship",
            workplace: "Design Studio",
            education: "Art School",
            phone: "987-654-3210",
            hometown: "Chicago",
            createdAt: "2023-01-01T00:00:00Z",
            updatedAt: "2023-01-01T00:00:00Z",
        },
        role: "USER",
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "3",
        email: "john.doe@example.com",
        gender: "MALE",
        fullName: "Bob Johnson",
        dateOfBirth: "2000-04-15",
        avatarPhotoUrl: "/placeholder.svg",
        coverPhotoUrl: "/cover-placeholder.svg",
        followers: [],
        following: [],
        posts: [],
        status: "ACTIVE",
        celebrity: false,
        friends: [{
            id: "2",
            email: "john.doe@example.com",
            gender: "MALE",
            fullName: "John Doe",
            dateOfBirth: "2000-04-15",
            avatarPhotoUrl: "/placeholder.svg",
            coverPhotoUrl: "/cover-placeholder.svg",
            followers: [],
            following: [],
            friends: [],
            posts: [],
            status: "ACTIVE",
            celebrity: false,
            bio: {
                id: "2",
                user: {} as USER,
                bioText: "Software Engineer",
                liveIn: "New York",
                relationship: "Single",
                workplace: "Tech Company",
                education: "University of Technology",
                phone: "123-456-7890",
                hometown: "Los Angeles",
                createdAt: "2023-01-01T00:00:00Z",
                updatedAt: "2023-01-01T00:00:00Z",
            },
            role: "USER",
            createdAt: "2023-01-01T00:00:00Z",
            updatedAt: "2023-01-01T00:00:00Z",
        },],
        bio: {
            id: "3",
            user: {} as USER,
            bioText: "Software Engineer",
            liveIn: "New York",
            relationship: "Single",
            workplace: "Tech Company",
            education: "University of Technology",
            phone: "123-456-7890",
            hometown: "Los Angeles",
            createdAt: "2023-01-01T00:00:00Z",
            updatedAt: "2023-01-01T00:00:00Z",
        },
        role: "USER",
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "4",
        email: "jane.smith@example.com",
        gender: "FEMALE",
        fullName: "Jane Smith",
        dateOfBirth: "1992-02-02",
        avatarPhotoUrl: "/placeholder.svg",
        coverPhotoUrl: "/cover-placeholder.svg",
        followers: [],
        following: [],
        posts: [],
        status: "ACTIVE",
        celebrity: false,
        friends: [{
            id: "2",
            email: "john.doe@example.com",
            gender: "MALE",
            fullName: "John Doe",
            dateOfBirth: "2000-04-15",
            avatarPhotoUrl: "/placeholder.svg",
            coverPhotoUrl: "/cover-placeholder.svg",
            followers: [],
            following: [],
            friends: [],
            posts: [],
            status: "ACTIVE",
            celebrity: false,
            bio: {
                id: "2",
                user: {} as USER,
                bioText: "Software Engineer",
                liveIn: "New York",
                relationship: "Single",
                workplace: "Tech Company",
                education: "University of Technology",
                phone: "123-456-7890",
                hometown: "Los Angeles",
                createdAt: "2023-01-01T00:00:00Z",
                updatedAt: "2023-01-01T00:00:00Z",
            },
            role: "USER",
            createdAt: "2023-01-01T00:00:00Z",
            updatedAt: "2023-01-01T00:00:00Z",
        },],
        bio: {
            id: "4",
            user: {} as USER,
            bioText: "Graphic Designer",
            liveIn: "San Francisco",
            relationship: "In a relationship",
            workplace: "Design Studio",
            education: "Art School",
            phone: "987-654-3210",
            hometown: "Chicago",
            createdAt: "2023-01-01T00:00:00Z",
            updatedAt: "2023-01-01T00:00:00Z",
        },
        role: "USER",
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "5",
        email: "john.doe@example.com",
        gender: "MALE",
        fullName: "John 5",
        dateOfBirth: "2000-04-15",
        avatarPhotoUrl: "/placeholder.svg",
        coverPhotoUrl: "/cover-placeholder.svg",
        followers: [],
        following: [],
        friends: [],
        posts: [],
        status: "ACTIVE",
        celebrity: false,
        bio: {
            id: "5",
            user: {} as USER,
            bioText: "Software Engineer",
            liveIn: "New York",
            relationship: "Single",
            workplace: "Tech Company",
            education: "University of Technology",
            phone: "123-456-7890",
            hometown: "Los Angeles",
            createdAt: "2023-01-01T00:00:00Z",
            updatedAt: "2023-01-01T00:00:00Z",
        },
        role: "USER",
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "6",
        email: "jane.smith@example.com",
        gender: "FEMALE",
        fullName: "Jane 6",
        dateOfBirth: "1992-02-02",
        avatarPhotoUrl: "/placeholder.svg",
        coverPhotoUrl: "/cover-placeholder.svg",
        followers: [],
        following: [],
        friends: [],
        posts: [],
        status: "ACTIVE",
        celebrity: false,
        bio: {
            id: "6",
            user: {} as USER,
            bioText: "Graphic Designer",
            liveIn: "San Francisco",
            relationship: "In a relationship",
            workplace: "Design Studio",
            education: "Art School",
            phone: "987-654-3210",
            hometown: "Chicago",
            createdAt: "2023-01-01T00:00:00Z",
            updatedAt: "2023-01-01T00:00:00Z",
        },
        role: "USER",
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "7",
        email: "john.doe@example.com",
        gender: "MALE",
        fullName: "John 7",
        dateOfBirth: "2000-04-15",
        avatarPhotoUrl: "/placeholder.svg",
        coverPhotoUrl: "/cover-placeholder.svg",
        followers: [],
        following: [],
        friends: [],
        posts: [],
        status: "ACTIVE",
        celebrity: false,
        bio: {
            id: "7",
            user: {} as USER,
            bioText: "Software Engineer",
            liveIn: "New York",
            relationship: "Single",
            workplace: "Tech Company",
            education: "University of Technology",
            phone: "123-456-7890",
            hometown: "Los Angeles",
            createdAt: "2023-01-01T00:00:00Z",
            updatedAt: "2023-01-01T00:00:00Z",
        },
        role: "USER",
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "8",
        email: "jane.smith@example.com",
        gender: "FEMALE",
        fullName: "Jane 8",
        dateOfBirth: "1992-02-02",
        avatarPhotoUrl: "/placeholder.svg",
        coverPhotoUrl: "/cover-placeholder.svg",
        followers: [],
        following: [],
        friends: [],
        posts: [],
        status: "ACTIVE",
        celebrity: false,
        bio: {
            id: "8",
            user: {} as USER,
            bioText: "Graphic Designer",
            liveIn: "San Francisco",
            relationship: "In a relationship",
            workplace: "Design Studio",
            education: "Art School",
            phone: "987-654-3210",
            hometown: "Chicago",
            createdAt: "2023-01-01T00:00:00Z",
            updatedAt: "2023-01-01T00:00:00Z",
        },
        role: "USER",
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "9",
        email: "john.doe@example.com",
        gender: "MALE",
        fullName: "John 9",
        dateOfBirth: "2000-04-15",
        avatarPhotoUrl: "/placeholder.svg",
        coverPhotoUrl: "/cover-placeholder.svg",
        followers: [],
        following: [],
        friends: [],
        posts: [],
        status: "ACTIVE",
        celebrity: false,
        bio: {
            id: "9",
            user: {} as USER,
            bioText: "Software Engineer",
            liveIn: "New York",
            relationship: "Single",
            workplace: "Tech Company",
            education: "University of Technology",
            phone: "123-456-7890",
            hometown: "Los Angeles",
            createdAt: "2023-01-01T00:00:00Z",
            updatedAt: "2023-01-01T00:00:00Z",
        },
        role: "USER",
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "10",
        email: "jane.smith@example.com",
        gender: "FEMALE",
        fullName: "Jane 10",
        dateOfBirth: "1992-02-02",
        avatarPhotoUrl: "/placeholder.svg",
        coverPhotoUrl: "/cover-placeholder.svg",
        followers: [],
        following: [],
        friends: [],
        posts: [],
        status: "ACTIVE",
        celebrity: false,
        bio: {
            id: "10",
            user: {} as USER,
            bioText: "Graphic Designer",
            liveIn: "San Francisco",
            relationship: "In a relationship",
            workplace: "Design Studio",
            education: "Art School",
            phone: "987-654-3210",
            hometown: "Chicago",
            createdAt: "2023-01-01T00:00:00Z",
            updatedAt: "2023-01-01T00:00:00Z",
        },
        role: "USER",
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
];

export const mockStories: STORY[] = [
    {
        id: "1",
        user: mockUsers[0],
        mediaUrl: "https://source.unsplash.com/featured/?sunset",
        mediaType: "IMAGE",
        privacy: "PUBLIC",
        createdAt: "2025-04-15T07:00:00Z",
        updatedAt: "2025-04-15T07:00:00Z"
    },
    {
        id: "2",
        user: mockUsers[1],
        mediaUrl: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
        mediaType: "VIDEO",
        privacy: "PUBLIC",
        createdAt: "2025-04-15T06:45:00Z",
        updatedAt: "2025-04-15T06:45:00Z"
    },
    {
        id: "3",
        user: mockUsers[0],
        mediaUrl: "https://source.unsplash.com/featured/?coffee",
        mediaType: "IMAGE",
        privacy: "PUBLIC",
        createdAt: "2025-04-14T22:15:00Z",
        updatedAt: "2025-04-14T22:15:00Z"
    },
    {
        id: "4",
        user: mockUsers[0],
        mediaUrl: "https://source.unsplash.com/featured/?coffee",
        mediaType: "IMAGE",
        privacy: "PUBLIC",
        createdAt: "2025-04-14T22:15:00Z",
        updatedAt: "2025-04-14T22:15:00Z"
    }
];

export const mockPosts: POST[] = [
    {
        id: "1",
        user: mockUsers[0],
        content: "Hello, world!",
        mediaUrls: ["https://facebook-server.s3.amazonaws.com/cc5b0674-f049-4c7a-94fb-d2679d062414-hình_nền_máy_tính.jpg", "https://facebook-server.s3.amazonaws.com/8925cd87-e0ea-4326-a26c-292bbe00fcff-6000108366034.mp4", "https://facebook-server.s3.amazonaws.com/cc5b0674-f049-4c7a-94fb-d2679d062414-hình_nền_máy_tính.jpg", "https://facebook-server.s3.amazonaws.com/8925cd87-e0ea-4326-a26c-292bbe00fcff-6000108366034.mp4", "https://facebook-server.s3.amazonaws.com/cc5b0674-f049-4c7a-94fb-d2679d062414-hình_nền_máy_tính.jpg"],
        mediaTypes: ["IMAGE", "VIDEO", "IMAGE", "VIDEO", "IMAGE"],
        privacy: "PUBLIC",
        likes: [],
        comments: [],
        share: [],
        createdAt: "2023-01-02T00:00:00Z",
        updatedAt: "2023-01-02T00:00:00Z",
    },
    {
        id: "2",
        user: mockUsers[0],
        content: "Hello, world!",
        mediaUrls: ["https://facebook-server.s3.amazonaws.com/cc5b0674-f049-4c7a-94fb-d2679d062414-hình_nền_máy_tính.jpg", "https://facebook-server.s3.amazonaws.com/8925cd87-e0ea-4326-a26c-292bbe00fcff-6000108366034.mp4", "https://facebook-server.s3.amazonaws.com/cc5b0674-f049-4c7a-94fb-d2679d062414-hình_nền_máy_tính.jpg", "https://facebook-server.s3.amazonaws.com/8925cd87-e0ea-4326-a26c-292bbe00fcff-6000108366034.mp4"],
        mediaTypes: ["IMAGE", "VIDEO", "IMAGE", "VIDEO"],
        privacy: "PUBLIC",
        likes: [],
        comments: [],
        share: [],
        createdAt: "2023-01-02T00:00:00Z",
        updatedAt: "2023-01-02T00:00:00Z",
    },
    {
        id: "3",
        user: mockUsers[0],
        content: "Hello, world!",
        mediaUrls: ["/media-placeholder.jpg"],
        mediaTypes: ["IMAGE"],
        privacy: "PUBLIC",
        likes: [],
        comments: [],
        share: [],
        createdAt: "2023-01-02T00:00:00Z",
        updatedAt: "2023-01-02T00:00:00Z",
    },
    {
        id: "4",
        user: mockUsers[0],
        content: "Hello, world!",
        mediaUrls: ["/media-placeholder.jpg"],
        mediaTypes: ["IMAGE"],
        privacy: "PUBLIC",
        likes: [],
        comments: [],
        share: [],
        createdAt: "2023-01-02T00:00:00Z",
        updatedAt: "2023-01-02T00:00:00Z",
    },
    {
        id: "5",
        user: mockUsers[0],
        content: "Hello, world!",
        mediaUrls: ["/media-placeholder.jpg"],
        mediaTypes: ["VIDEO"],
        privacy: "PUBLIC",
        likes: [],
        comments: [],
        share: [],
        createdAt: "2023-01-02T00:00:00Z",
        updatedAt: "2023-01-02T00:00:00Z",
    },
    {
        id: "6",
        user: mockUsers[0],
        content: "Hello, world!",
        mediaUrls: ["/media-placeholder.jpg"],
        mediaTypes: ["VIDEO"],
        privacy: "PUBLIC",
        likes: [],
        comments: [],
        share: [],
        createdAt: "2023-01-02T00:00:00Z",
        updatedAt: "2023-01-02T00:00:00Z",
    },
    {
        id: "7",
        user: mockUsers[0],
        content: "Hello, world!",
        mediaUrls: ["/media-placeholder.jpg"],
        mediaTypes: ["VIDEO"],
        privacy: "PUBLIC",
        likes: [],
        comments: [],
        share: [],
        createdAt: "2023-01-02T00:00:00Z",
        updatedAt: "2023-01-02T00:00:00Z",
    },
    {
        id: "8",
        user: mockUsers[0],
        content: "Hello, world!",
        mediaUrls: ["/media-placeholder.jpg"],
        mediaTypes: ["VIDEO"],
        privacy: "PUBLIC",
        likes: [],
        comments: [],
        share: [],
        createdAt: "2023-01-02T00:00:00Z",
        updatedAt: "2023-01-02T00:00:00Z",
    },
    {
        id: "9",
        user: mockUsers[0],
        content: "Hello, world!",
        mediaUrls: ["/media-placeholder.jpg"],
        mediaTypes: ["VIDEO"],
        privacy: "PUBLIC",
        likes: [],
        comments: [],
        share: [],
        createdAt: "2023-01-02T00:00:00Z",
        updatedAt: "2023-01-02T00:00:00Z",
    },
    {
        id: "10",
        user: mockUsers[0],
        content: "Hello, world!",
        mediaUrls: ["/media-placeholder.jpg"],
        mediaTypes: ["VIDEO"],
        privacy: "PUBLIC",
        likes: [],
        comments: [],
        share: [],
        createdAt: "2023-01-02T00:00:00Z",
        updatedAt: "2023-01-02T00:00:00Z",
    },
];

export const mockComments: COMMENT[] = [
    {
        id: "1",
        user: mockUsers[1],
        text: "Nice post!",
        createdAt: "2023-01-02T01:00:00Z",
        updatedAt: "2023-01-02T01:00:00Z",
    },
];

export const mockMessages = [
    {
        id: "1",
        text: "Hey there!",
        sender: "user",
        timestamp: new Date(Date.now() - 1000 * 60 * 5),
    },
    {
        id: "2",
        text: "Hi! How are you?",
        sender: "me",
        timestamp: new Date(Date.now() - 1000 * 60 * 4),
    },
    {
        id: "3",
        text: "I'm good, thanks for asking. What about you?",
        sender: "user",
        timestamp: new Date(Date.now() - 1000 * 60 * 3),
    },
    {
        id: "4",
        text: "I'm good, thanks for asking. What about you?",
        sender: "user",
        timestamp: new Date(Date.now() - 1000 * 60 * 3),
    },
    {
        id: "5",
        text: "I'm good, thanks for asking. What about you?",
        sender: "user",
        timestamp: new Date(Date.now() - 1000 * 60 * 3),
    },
    {
        id: "6",
        text: "I'm good, thanks for asking. What about you?",
        sender: "user",
        timestamp: new Date(Date.now() - 1000 * 60 * 3),
    },
];

export const mockUserChats = [
    {
        id: "1",
        user: mockUsers[1],
        lastMessage: "Hey, how are you doing?",
        time: "2m",
        unread: true,
        online: true,
    },
    {
        id: "2",
        user: mockUsers[2],
        lastMessage: "Can we meet tomorrow?",
        time: "1h",
        unread: true,
        online: true,
    },
    {
        id: "3",
        user: mockUsers[3],
        lastMessage: "Thanks for your help!",
        time: "3h",
        unread: true,
        online: false,
    },
    {
        id: "4",
        user: mockUsers[4],
        lastMessage: "I'll send you the files later",
        time: "1d",
        unread: false,
        online: true,
    },
    {
        id: "5",
        user: mockUsers[5],
        lastMessage: "See you at the meeting",
        time: "2d",
        unread: false,
        online: false,
    },
    {
        id: "6",
        user: mockUsers[6],
        lastMessage: "See you at the meeting",
        time: "2d",
        unread: false,
        online: false,
    },
];

export const mockNotifications: NOTIFICATION[] = [
    {
        id: "1",
        from: mockUsers[1],
        to: mockUsers[0],
        type: "FOLLOW",
        read: false,
        createdAt: "2023-01-04T00:00:00Z",
        updatedAt: "2023-01-04T00:00:00Z",
    },
];

export const mockFriendRequests: FRIEND_REQUEST[] = [
    {
        id: "1",
        from: mockUsers[3],
        to: mockUsers[0],
        status: "PENDING",
        createdAt: "2023-01-05T00:00:00Z",
        updatedAt: "2023-01-05T00:00:00Z",
    },
    {
        id: "2",
        from: mockUsers[4],
        to: mockUsers[0],
        status: "PENDING",
        createdAt: "2023-01-05T00:00:00Z",
        updatedAt: "2023-01-05T00:00:00Z",
    },
    {
        id: "3",
        from: mockUsers[5],
        to: mockUsers[0],
        status: "PENDING",
        createdAt: "2023-01-05T00:00:00Z",
        updatedAt: "2023-01-05T00:00:00Z",
    },
    {
        id: "4",
        from: mockUsers[6],
        to: mockUsers[0],
        status: "PENDING",
        createdAt: "2023-01-05T00:00:00Z",
        updatedAt: "2023-01-05T00:00:00Z",
    },
    {
        id: "5",
        from: mockUsers[7],
        to: mockUsers[0],
        status: "PENDING",
        createdAt: "2023-01-05T00:00:00Z",
        updatedAt: "2023-01-05T00:00:00Z",
    },
];

// Sample data for group conversations
export const mockGroupConversations = [
    {
        id: "1",
        name: "Design Team",
        participants: 5,
        avatarPhotoUrl: "/placeholder.svg?height=40&width=40",
        active: true,
    },
    {
        id: "2",
        name: "Weekend Trip Planning",
        participants: 8,
        avatarPhotoUrl: "/placeholder.svg?height=40&width=40",
        active: false,
    },
    {
        id: "3",
        name: "Gaming Squad",
        participants: 4,
        avatarPhotoUrl: "/placeholder.svg?height=40&width=40",
        active: true,
    },
];

export const mockStats: STATS = {
    totalUsers: 1500,
    totalPosts: 3000,
    totalComments: 5000,
    totalReports: 100,
}

export const mockReports: REPORT[] = [
    {
        id: "r1",
        sender: mockUsers[1],
        content: mockPosts[0],
        contentType: "POST",
        reason: "Nội dung không phù hợp",
        additionalInfo: "Có hình ảnh nhạy cảm không phù hợp với công cộng.",
        status: "PENDING",
        createdAt: "2025-04-20T10:00:00Z",
        updatedAt: "2025-04-20T10:00:00Z",
    },
    {
        id: "r2",
        sender: mockUsers[0],
        content: mockComments[0],
        contentType: "COMMENT",
        reason: "Spam",
        additionalInfo: "Bình luận này được lặp lại nhiều lần trên các bài khác.",
        status: "ACCEPT",
        createdAt: "2025-04-21T14:30:00Z",
        updatedAt: "2025-04-21T14:30:00Z",
    },
    {
        id: "r3",
        sender: mockUsers[1],
        content: mockUsers[0],
        contentType: "USER",
        reason: "Tài khoản giả mạo",
        additionalInfo: "Người này dùng tên và hình ảnh giống người nổi tiếng.",
        status: "REJECT",
        createdAt: "2025-04-22T08:15:00Z",
        updatedAt: "2025-04-22T08:15:00Z",
    },
    {
        id: "r4",
        sender: mockUsers[1],
        content: mockPosts[0],
        contentType: "POST",
        reason: "Nội dung không phù hợp",
        additionalInfo: "Có hình ảnh nhạy cảm không phù hợp với công cộng.",
        status: "PENDING",
        createdAt: "2025-04-20T10:00:00Z",
        updatedAt: "2025-04-20T10:00:00Z",
    },
    {
        id: "r5",
        sender: mockUsers[0],
        content: mockComments[0],
        contentType: "COMMENT",
        reason: "Spam",
        additionalInfo: "Bình luận này được lặp lại nhiều lần trên các bài khác.",
        status: "ACCEPT",
        createdAt: "2025-04-21T14:30:00Z",
        updatedAt: "2025-04-21T14:30:00Z",
    },
    {
        id: "r6",
        sender: mockUsers[1],
        content: mockUsers[0],
        contentType: "USER",
        reason: "Tài khoản giả mạo",
        additionalInfo: "Người này dùng tên và hình ảnh giống người nổi tiếng.",
        status: "REJECT",
        createdAt: "2025-04-22T08:15:00Z",
        updatedAt: "2025-04-22T08:15:00Z",
    },
    {
        id: "r7",
        sender: mockUsers[1],
        content: mockPosts[0],
        contentType: "POST",
        reason: "Nội dung không phù hợp",
        additionalInfo: "Có hình ảnh nhạy cảm không phù hợp với công cộng.",
        status: "PENDING",
        createdAt: "2025-04-20T10:00:00Z",
        updatedAt: "2025-04-20T10:00:00Z",
    },
    {
        id: "r8",
        sender: mockUsers[0],
        content: mockComments[0],
        contentType: "COMMENT",
        reason: "Spam",
        additionalInfo: "Bình luận này được lặp lại nhiều lần trên các bài khác.",
        status: "ACCEPT",
        createdAt: "2025-04-21T14:30:00Z",
        updatedAt: "2025-04-21T14:30:00Z",
    },
    {
        id: "r9",
        sender: mockUsers[1],
        content: mockUsers[0],
        contentType: "USER",
        reason: "Tài khoản giả mạo",
        additionalInfo: "Người này dùng tên và hình ảnh giống người nổi tiếng.",
        status: "REJECT",
        createdAt: "2025-04-22T08:15:00Z",
        updatedAt: "2025-04-22T08:15:00Z",
    }
];