import {
    USER,
    POST,
    COMMENT,
    // MESSAGE,
    NOTIFICATION,
    FRIEND_REQUEST,
    STORY
} from "./types";

export const mockUsers: USER[] = [
    {
        id: "1",
        email: "john.doe@example.com",
        gender: "male",
        fullName: "John Doe",
        dateOfBirth: "2000-04-15",
        avatarPhotoUrl: "/placeholder.svg",
        coverPhotoUrl: "/cover-placeholder.svg",
        followers: [],
        following: [],
        friends: [{
            id: "2",
            email: "john.doe@example.com",
            gender: "male",
            fullName: "John Doe",
            dateOfBirth: "2000-04-15",
            avatarPhotoUrl: "/placeholder.svg",
            coverPhotoUrl: "/cover-placeholder.svg",
            followers: [],
            following: [],
            friends: [],
            bio: {
                id: "2",
                user: {} as USER,
                bioText: "Software Engineer",
                liveIn: "New York",
                relationship: "Single",
                workplace: "Tech Company",
                education: "University of Technology",
                phone: "123-456-7890",
                hometown: "Los Angeles",
                createdAt: "2023-01-01T00:00:00Z",
                updatedAt: "2023-01-01T00:00:00Z",
            },
            role: "user",
            createdAt: "2023-01-01T00:00:00Z",
            updatedAt: "2023-01-01T00:00:00Z",
        },],
        bio: {
            id: "1",
            user: {} as USER,
            bioText: "Software Engineer",
            liveIn: "New York",
            relationship: "Single",
            workplace: "Tech Company",
            education: "University of Technology",
            phone: "123-456-7890",
            hometown: "Los Angeles",
            createdAt: "2023-01-01T00:00:00Z",
            updatedAt: "2023-01-01T00:00:00Z",
        },
        role: "admin",
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "2",
        email: "jane.smith@example.com",
        gender: "female",
        fullName: "Jane Smith",
        dateOfBirth: "1992-02-02",
        avatarPhotoUrl: "/placeholder.svg",
        coverPhotoUrl: "/cover-placeholder.svg",
        followers: [],
        following: [],
        friends: [{
            id: "1",
            email: "john.doe@example.com",
            gender: "male",
            fullName: "John Doe",
            dateOfBirth: "2000-04-15",
            avatarPhotoUrl: "/placeholder.svg",
            coverPhotoUrl: "/cover-placeholder.svg",
            followers: [],
            following: [],
            friends: [],
            bio: {
                id: "1",
                user: {} as USER,
                bioText: "Software Engineer",
                liveIn: "New York",
                relationship: "Single",
                workplace: "Tech Company",
                education: "University of Technology",
                phone: "123-456-7890",
                hometown: "Los Angeles",
                createdAt: "2023-01-01T00:00:00Z",
                updatedAt: "2023-01-01T00:00:00Z",
            },
            role: "user",
            createdAt: "2023-01-01T00:00:00Z",
            updatedAt: "2023-01-01T00:00:00Z",
        },],
        bio: {
            id: "2",
            user: {} as USER,
            bioText: "Graphic Designer",
            liveIn: "Alice Williams",
            relationship: "In a relationship",
            workplace: "Design Studio",
            education: "Art School",
            phone: "987-654-3210",
            hometown: "Chicago",
            createdAt: "2023-01-01T00:00:00Z",
            updatedAt: "2023-01-01T00:00:00Z",
        },
        role: "user",
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "3",
        email: "john.doe@example.com",
        gender: "male",
        fullName: "Bob Johnson",
        dateOfBirth: "2000-04-15",
        avatarPhotoUrl: "/placeholder.svg",
        coverPhotoUrl: "/cover-placeholder.svg",
        followers: [],
        following: [],
        friends: [{
            id: "2",
            email: "john.doe@example.com",
            gender: "male",
            fullName: "John Doe",
            dateOfBirth: "2000-04-15",
            avatarPhotoUrl: "/placeholder.svg",
            coverPhotoUrl: "/cover-placeholder.svg",
            followers: [],
            following: [],
            friends: [],
            bio: {
                id: "2",
                user: {} as USER,
                bioText: "Software Engineer",
                liveIn: "New York",
                relationship: "Single",
                workplace: "Tech Company",
                education: "University of Technology",
                phone: "123-456-7890",
                hometown: "Los Angeles",
                createdAt: "2023-01-01T00:00:00Z",
                updatedAt: "2023-01-01T00:00:00Z",
            },
            role: "user",
            createdAt: "2023-01-01T00:00:00Z",
            updatedAt: "2023-01-01T00:00:00Z",
        },],
        bio: {
            id: "3",
            user: {} as USER,
            bioText: "Software Engineer",
            liveIn: "New York",
            relationship: "Single",
            workplace: "Tech Company",
            education: "University of Technology",
            phone: "123-456-7890",
            hometown: "Los Angeles",
            createdAt: "2023-01-01T00:00:00Z",
            updatedAt: "2023-01-01T00:00:00Z",
        },
        role: "user",
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "4",
        email: "jane.smith@example.com",
        gender: "female",
        fullName: "Jane Smith",
        dateOfBirth: "1992-02-02",
        avatarPhotoUrl: "/placeholder.svg",
        coverPhotoUrl: "/cover-placeholder.svg",
        followers: [],
        following: [],
        friends: [{
            id: "2",
            email: "john.doe@example.com",
            gender: "male",
            fullName: "John Doe",
            dateOfBirth: "2000-04-15",
            avatarPhotoUrl: "/placeholder.svg",
            coverPhotoUrl: "/cover-placeholder.svg",
            followers: [],
            following: [],
            friends: [],
            bio: {
                id: "2",
                user: {} as USER,
                bioText: "Software Engineer",
                liveIn: "New York",
                relationship: "Single",
                workplace: "Tech Company",
                education: "University of Technology",
                phone: "123-456-7890",
                hometown: "Los Angeles",
                createdAt: "2023-01-01T00:00:00Z",
                updatedAt: "2023-01-01T00:00:00Z",
            },
            role: "user",
            createdAt: "2023-01-01T00:00:00Z",
            updatedAt: "2023-01-01T00:00:00Z",
        },],
        bio: {
            id: "4",
            user: {} as USER,
            bioText: "Graphic Designer",
            liveIn: "San Francisco",
            relationship: "In a relationship",
            workplace: "Design Studio",
            education: "Art School",
            phone: "987-654-3210",
            hometown: "Chicago",
            createdAt: "2023-01-01T00:00:00Z",
            updatedAt: "2023-01-01T00:00:00Z",
        },
        role: "user",
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "5",
        email: "john.doe@example.com",
        gender: "male",
        fullName: "John 5",
        dateOfBirth: "2000-04-15",
        avatarPhotoUrl: "/placeholder.svg",
        coverPhotoUrl: "/cover-placeholder.svg",
        followers: [],
        following: [],
        friends: [],
        bio: {
            id: "5",
            user: {} as USER,
            bioText: "Software Engineer",
            liveIn: "New York",
            relationship: "Single",
            workplace: "Tech Company",
            education: "University of Technology",
            phone: "123-456-7890",
            hometown: "Los Angeles",
            createdAt: "2023-01-01T00:00:00Z",
            updatedAt: "2023-01-01T00:00:00Z",
        },
        role: "user",
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "6",
        email: "jane.smith@example.com",
        gender: "female",
        fullName: "Jane 6",
        dateOfBirth: "1992-02-02",
        avatarPhotoUrl: "/placeholder.svg",
        coverPhotoUrl: "/cover-placeholder.svg",
        followers: [],
        following: [],
        friends: [],
        bio: {
            id: "6",
            user: {} as USER,
            bioText: "Graphic Designer",
            liveIn: "San Francisco",
            relationship: "In a relationship",
            workplace: "Design Studio",
            education: "Art School",
            phone: "987-654-3210",
            hometown: "Chicago",
            createdAt: "2023-01-01T00:00:00Z",
            updatedAt: "2023-01-01T00:00:00Z",
        },
        role: "user",
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "7",
        email: "john.doe@example.com",
        gender: "male",
        fullName: "John 7",
        dateOfBirth: "2000-04-15",
        avatarPhotoUrl: "/placeholder.svg",
        coverPhotoUrl: "/cover-placeholder.svg",
        followers: [],
        following: [],
        friends: [],
        bio: {
            id: "7",
            user: {} as USER,
            bioText: "Software Engineer",
            liveIn: "New York",
            relationship: "Single",
            workplace: "Tech Company",
            education: "University of Technology",
            phone: "123-456-7890",
            hometown: "Los Angeles",
            createdAt: "2023-01-01T00:00:00Z",
            updatedAt: "2023-01-01T00:00:00Z",
        },
        role: "user",
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "8",
        email: "jane.smith@example.com",
        gender: "female",
        fullName: "Jane 8",
        dateOfBirth: "1992-02-02",
        avatarPhotoUrl: "/placeholder.svg",
        coverPhotoUrl: "/cover-placeholder.svg",
        followers: [],
        following: [],
        friends: [],
        bio: {
            id: "8",
            user: {} as USER,
            bioText: "Graphic Designer",
            liveIn: "San Francisco",
            relationship: "In a relationship",
            workplace: "Design Studio",
            education: "Art School",
            phone: "987-654-3210",
            hometown: "Chicago",
            createdAt: "2023-01-01T00:00:00Z",
            updatedAt: "2023-01-01T00:00:00Z",
        },
        role: "user",
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "9",
        email: "john.doe@example.com",
        gender: "male",
        fullName: "John 9",
        dateOfBirth: "2000-04-15",
        avatarPhotoUrl: "/placeholder.svg",
        coverPhotoUrl: "/cover-placeholder.svg",
        followers: [],
        following: [],
        friends: [],
        bio: {
            id: "9",
            user: {} as USER,
            bioText: "Software Engineer",
            liveIn: "New York",
            relationship: "Single",
            workplace: "Tech Company",
            education: "University of Technology",
            phone: "123-456-7890",
            hometown: "Los Angeles",
            createdAt: "2023-01-01T00:00:00Z",
            updatedAt: "2023-01-01T00:00:00Z",
        },
        role: "user",
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
    {
        id: "10",
        email: "jane.smith@example.com",
        gender: "female",
        fullName: "Jane 10",
        dateOfBirth: "1992-02-02",
        avatarPhotoUrl: "/placeholder.svg",
        coverPhotoUrl: "/cover-placeholder.svg",
        followers: [],
        following: [],
        friends: [],
        bio: {
            id: "10",
            user: {} as USER,
            bioText: "Graphic Designer",
            liveIn: "San Francisco",
            relationship: "In a relationship",
            workplace: "Design Studio",
            education: "Art School",
            phone: "987-654-3210",
            hometown: "Chicago",
            createdAt: "2023-01-01T00:00:00Z",
            updatedAt: "2023-01-01T00:00:00Z",
        },
        role: "user",
        createdAt: "2023-01-01T00:00:00Z",
        updatedAt: "2023-01-01T00:00:00Z",
    },
];

export const mockStories: STORY[] = [
    {
        id: "1",
        user: mockUsers[0],
        mediaUrl: "https://source.unsplash.com/featured/?sunset",
        mediaType: "image",
        createdAt: "2025-04-15T07:00:00Z",
        updatedAt: "2025-04-15T07:00:00Z"
    },
    {
        id: "2",
        user: mockUsers[1],
        mediaUrl: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
        mediaType: "video",
        createdAt: "2025-04-15T06:45:00Z",
        updatedAt: "2025-04-15T06:45:00Z"
    },
    {
        id: "3",
        user: mockUsers[0],
        mediaUrl: "https://source.unsplash.com/featured/?coffee",
        mediaType: "image",
        createdAt: "2025-04-14T22:15:00Z",
        updatedAt: "2025-04-14T22:15:00Z"
    },
    {
        id: "4",
        user: mockUsers[0],
        mediaUrl: "https://source.unsplash.com/featured/?coffee",
        mediaType: "image",
        createdAt: "2025-04-14T22:15:00Z",
        updatedAt: "2025-04-14T22:15:00Z"
    }
];

export const mockPosts: POST[] = [
    {
        id: "1",
        user: mockUsers[0],
        content: "Hello, world!",
        mediaUrl: "/media-placeholder.jpg",
        mediaType: "image",
        likes: [],
        comments: [],
        shares: [],
        createdAt: "2023-01-02T00:00:00Z",
        updatedAt: "2023-01-02T00:00:00Z",
    },
    {
        id: "2",
        user: mockUsers[0],
        content: "Hello, world!",
        mediaUrl: "/media-placeholder.jpg",
        mediaType: "image",
        likes: [],
        comments: [],
        shares: [],
        createdAt: "2023-01-02T00:00:00Z",
        updatedAt: "2023-01-02T00:00:00Z",
    },
    {
        id: "3",
        user: mockUsers[0],
        content: "Hello, world!",
        mediaUrl: "/media-placeholder.jpg",
        mediaType: "image",
        likes: [],
        comments: [],
        shares: [],
        createdAt: "2023-01-02T00:00:00Z",
        updatedAt: "2023-01-02T00:00:00Z",
    },
    {
        id: "4",
        user: mockUsers[0],
        content: "Hello, world!",
        mediaUrl: "/media-placeholder.jpg",
        mediaType: "image",
        likes: [],
        comments: [],
        shares: [],
        createdAt: "2023-01-02T00:00:00Z",
        updatedAt: "2023-01-02T00:00:00Z",
    },
    {
        id: "5",
        user: mockUsers[0],
        content: "Hello, world!",
        mediaUrl: "/media-placeholder.jpg",
        mediaType: "video",
        likes: [],
        comments: [],
        shares: [],
        createdAt: "2023-01-02T00:00:00Z",
        updatedAt: "2023-01-02T00:00:00Z",
    },
    {
        id: "6",
        user: mockUsers[0],
        content: "Hello, world!",
        mediaUrl: "/media-placeholder.jpg",
        mediaType: "video",
        likes: [],
        comments: [],
        shares: [],
        createdAt: "2023-01-02T00:00:00Z",
        updatedAt: "2023-01-02T00:00:00Z",
    },
    {
        id: "7",
        user: mockUsers[0],
        content: "Hello, world!",
        mediaUrl: "/media-placeholder.jpg",
        mediaType: "video",
        likes: [],
        comments: [],
        shares: [],
        createdAt: "2023-01-02T00:00:00Z",
        updatedAt: "2023-01-02T00:00:00Z",
    },
];

export const mockComments: COMMENT[] = [
    {
        id: "1",
        user: mockUsers[1],
        text: "Nice post!",
        createdAt: "2023-01-02T01:00:00Z",
        updatedAt: "2023-01-02T01:00:00Z",
    },
];

// export const mockMessages: MESSAGE[] = [
//     {
//         id: "1",
//         sender: mockUsers[0],
//         receiver: mockUsers[1],
//         content: "Hey, how are you?",
//         createdAt: "2023-01-03T00:00:00Z",
//         updatedAt: "2023-01-03T00:00:00Z",
//     },
// ];

export const mockMessages = [
    {
        id: "1",
        text: "Hey there!",
        sender: "user",
        timestamp: new Date(Date.now() - 1000 * 60 * 5),
    },
    {
        id: "2",
        text: "Hi! How are you?",
        sender: "me",
        timestamp: new Date(Date.now() - 1000 * 60 * 4),
    },
    {
        id: "3",
        text: "I'm good, thanks for asking. What about you?",
        sender: "user",
        timestamp: new Date(Date.now() - 1000 * 60 * 3),
    },
    {
        id: "4",
        text: "I'm good, thanks for asking. What about you?",
        sender: "user",
        timestamp: new Date(Date.now() - 1000 * 60 * 3),
    },
    {
        id: "5",
        text: "I'm good, thanks for asking. What about you?",
        sender: "user",
        timestamp: new Date(Date.now() - 1000 * 60 * 3),
    },
    {
        id: "6",
        text: "I'm good, thanks for asking. What about you?",
        sender: "user",
        timestamp: new Date(Date.now() - 1000 * 60 * 3),
    },
];

export const mockUserChats = [
    {
        id: "1",
        user: {
            id: "user1",
            name: "John Doe",
            avatar: "/placeholder.svg?height=40&width=40",
        },
        lastMessage: "Hey, how are you doing?",
        time: "2m",
        unread: true,
        online: true,
    },
    {
        id: "2",
        user: {
            id: "user2",
            name: "Jane Smith",
            avatar: "/placeholder.svg?height=40&width=40",
        },
        lastMessage: "Can we meet tomorrow?",
        time: "1h",
        unread: true,
        online: true,
    },
    {
        id: "3",
        user: {
            id: "user3",
            name: "Mike Johnson",
            avatar: "/placeholder.svg?height=40&width=40",
        },
        lastMessage: "Thanks for your help!",
        time: "3h",
        unread: true,
        online: false,
    },
    {
        id: "4",
        user: {
            id: "user4",
            name: "Sarah Williams",
            avatar: "/placeholder.svg?height=40&width=40",
        },
        lastMessage: "I'll send you the files later",
        time: "1d",
        unread: false,
        online: true,
    },
    {
        id: "5",
        user: {
            id: "user5",
            name: "David Brown",
            avatar: "/placeholder.svg?height=40&width=40",
        },
        lastMessage: "See you at the meeting",
        time: "2d",
        unread: false,
        online: false,
    },
    {
        id: "6",
        user: {
            id: "user6",
            name: "John ci",
            avatar: "/placeholder.svg?height=40&width=40",
        },
        lastMessage: "See you at the meeting",
        time: "2d",
        unread: false,
        online: false,
    },
];

export const mockNotifications: NOTIFICATION[] = [
    {
        id: "1",
        from: mockUsers[1],
        to: mockUsers[0],
        type: "friend_request",
        read: false,
        createdAt: "2023-01-04T00:00:00Z",
        updatedAt: "2023-01-04T00:00:00Z",
    },
];

export const mockFriendRequests: FRIEND_REQUEST[] = [
    {
        id: "1",
        from: mockUsers[3],
        to: mockUsers[0],
        status: "pending",
        createdAt: "2023-01-05T00:00:00Z",
        updatedAt: "2023-01-05T00:00:00Z",
    },
    {
        id: "2",
        from: mockUsers[4],
        to: mockUsers[0],
        status: "pending",
        createdAt: "2023-01-05T00:00:00Z",
        updatedAt: "2023-01-05T00:00:00Z",
    },
    {
        id: "3",
        from: mockUsers[5],
        to: mockUsers[0],
        status: "pending",
        createdAt: "2023-01-05T00:00:00Z",
        updatedAt: "2023-01-05T00:00:00Z",
    },
    {
        id: "4",
        from: mockUsers[6],
        to: mockUsers[0],
        status: "pending",
        createdAt: "2023-01-05T00:00:00Z",
        updatedAt: "2023-01-05T00:00:00Z",
    },
    {
        id: "5",
        from: mockUsers[7],
        to: mockUsers[0],
        status: "pending",
        createdAt: "2023-01-05T00:00:00Z",
        updatedAt: "2023-01-05T00:00:00Z",
    },
];

// Sample data for group conversations
export const mockGroupConversations = [
    {
        id: "1",
        name: "Design Team",
        participants: 5,
        avatarPhotoUrl: "/placeholder.svg?height=40&width=40",
        active: true,
    },
    {
        id: "2",
        name: "Weekend Trip Planning",
        participants: 8,
        avatarPhotoUrl: "/placeholder.svg?height=40&width=40",
        active: false,
    },
    {
        id: "3",
        name: "Gaming Squad",
        participants: 4,
        avatarPhotoUrl: "/placeholder.svg?height=40&width=40",
        active: true,
    },
];